#!/bin/sh
BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`

bat=/sys/class/power_supply/${BAT}/

percentage="$(cat "$bat/capacity")"
status=$(cat "$bat/status")

icon() {
    [ $status = Full ] && echo "󰂄" && exit
    [ $status = Charging ] && echo "" && exit

    if [ "$percentage" -gt "90" ]; then
        icon="󰁹"
    elif [ "$percentage" -gt "80" ]; then
        icon="󰂂"
    elif [ "$percentage" -gt "70" ]; then
        icon="󰂁"
    elif [ "$percentage" -gt "60" ]; then
        icon="󰂀"
    elif [ "$percentage" -gt "50" ]; then
        icon="󰁿"
    elif [ "$percentage" -gt "40" ]; then
        icon="󰁾"
    elif [ "$percentage" -gt "30" ]; then
        icon="󰁽"
    elif [ "$percentage" -gt "20" ]; then
        icon="󰁼"
    elif [ "$percentage" -gt "10" ]; then
        icon="󰁻"
        notify-send "Battery Low" "${percentage} left"
    elif [ "$percentage" -gt "0" ]; then
        icon="󰁺"
        notify-send -u critical "Battery Low" "${percentage} left"
    else
            echo 󰂃 && exit
    fi

    echo "$icon"
}

percent() {
    echo $percentage
}

status(){
    echo $status
}
[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "status" ] && status && exit
exit