#!/usr/bin/env bash
# https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#configewwscriptsget-workspaces
spaces (){
  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')

  # modified to only go to max visible workspace
  ar=(`hyprctl workspaces | grep "workspace ID" | cut -d' ' -f 3`)

  max=${ar[0]}
  for n in "${ar[@]}" ; do
      ((n > max)) && max=$n
  done

  seq 1 $max | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  spaces
done