#!/bin/sh

cmd=`playerctl metadata --format '{"title": "{{trunc(markup_escape(title), 50)}}", "artist": "{{artist}}", "class": "{{playerName}}", "icon": "{{mpris:artUrl}}", "length": "{{mpris:length}}", "lengthf": "{{duration(mpris:length)}}", "positionf": "{{duration(position)}}", "position": "{{position}}", "status": "{{status}}"  }'`

declare -A replaces
replaces["&quot;"]="\\\\\""
replaces["&apost;"]="'"
replaces["&lt;"]="<"
replaces["&gt;"]=">"
replaces["&amp;"]="&"

for key in "${!replaces[@]}"
do
    cmd=`echo "$cmd" | sed -r "s/$key/${replaces[$key]}/g"`
done
echo $cmd